server:
  port: 8088
  servlet:
    context-path: /dev
logging:
  level:
    root: info
    cn.bug: debug

enviroment: notebook

spring:
  redis:
    database: 0
    host: 192.168.11.128         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: 1234             # Redis服务器连接密码（默认为空）
    timeout: 1000         # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 16    # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0    # 连接池中的最小空闲连接
    url:

  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  # 数据源配置
  datasource:
    oracledb-parent: # 数据源1
      driver-class-name: oracle.jdbc.OracleDriver
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
    sqldb-parent: # 数据源1
      driver-class-name: net.sourceforge.jtds.jdbc.Driver
      #      url: jdbc:jtds:sqlserver://172.16.1.253/JSDerik_erp_dta
      #      username: sa
      #      password: JSDerik@2019
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
    mysqldb-parent: # 数据源1
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:jtds:sqlserver://172.16.1.253/JSDerik_erp_dta
      #      username: sa
      #      password: JSDerik@2019
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
    erpdta:
      #      url: jdbc:jtds:sqlserver://172.16.3.191/JSDerik_erp_dta
      url: jdbc:jtds:sqlserver://172.16.30.100/JSDerik_erp_dta_T
      username: sa
      password: dali888
    security-jwt-vue-db:
      #      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.11.128:3306/security_jwt_vue
      username: root
      password: 1234
    #    mes-api-db:
    #      url: jdbc:jtds:sqlserver://172.16.3.191/Derik_MES_API
    #      username: sa
    #      password: derik888
    #    qms-db:
    #      url: jdbc:oracle:thin:@172.16.2.35:1521:DERIKMESDB
    #      username: U_TEST
    #      password: U_TEST
    type: com.alibaba.druid.pool.DruidDataSource
    # MYSQL 5 驱动：com.mysql.jdbc.Driver，MYSQL 6+ 驱动：com.mysql.cj.jdbc.Driver
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        #        allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
        #        deny: 192.168.31.253
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: root
        login-password: 123
        enabled: true
  security:
    user:
      name: admin
      password: 1234

mybatis-plus:
  #  type-aliases-package: cn.bug.springdemo01
  #  mapper-locations: mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      #      logic-delete-field: isDel  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: true # 逻辑已删除值(默认为 1)
      logic-not-delete-value: false # 逻辑未删除值(默认为 0)
      logic-delete-field: isDel
